//! The starter scenes, written with Jackdaw's own BSN writer: the lobby
//! (one `LobbyEntry` per built-in experience) and two example scenes.
//! `cargo run --example generate_scenes` writes them to `assets/`, and a
//! test checks the committed files are current.

/// Builds one scene's `.bsn` text.
pub type SceneText = fn() -> String;

/// Each scene's path under `assets/`, and how to build its text.
pub const SCENES: [(&str, SceneText); 3] = [
    ("lobby.bsn", lobby),
    ("examples/perceptron.bsn", perceptron),
    ("examples/loss-shapes.bsn", loss_shapes),
];

use bevaru::authoring::{LobbyEntry, LossShapeSurface, PerceptronDiagram};
use bevaru::experiences::{ExperienceRegistry, ExperiencesPlugin};
use bevy::prelude::*;

/// A world whose type registry knows bevaru's authorable components.
pub fn world() -> App {
    let mut app = App::new();
    app.add_plugins(bevaru::authoring::AuthoringPlugin)
        .register_type::<Transform>()
        .register_type::<Visibility>()
        .register_type::<Camera3d>()
        .register_type::<DirectionalLight>();
    app
}

fn bsn(app: &App, header: &str) -> String {
    // Like the editor's own scenes: keep `Visibility`, and leave out the
    // camera's and light's required components, which Bevy adds back on load.
    let config = jackdaw_bsn::BsnWriterConfig::default()
        .always_save("bevy_camera::visibility::Visibility")
        .skip_prefix("bevy_camera::camera::")
        .skip_prefix("bevy_camera::projection::")
        .skip_path("bevy_light::cascade::CascadeShadowConfig");
    let text = jackdaw_bsn::serialize_to_bsn_with_config(app.world(), &config);
    format!("{header}\n\n{text}")
}

/// `lobby.bsn`: one `LobbyEntry` per built-in experience, in lobby order.
pub fn lobby() -> String {
    let mut registry_app = App::new();
    registry_app.add_plugins(ExperiencesPlugin);
    let registry = registry_app.world().resource::<ExperienceRegistry>();
    let mut app = world();
    let world = app.world_mut();
    let entries: Vec<Entity> = registry
        .iter()
        .enumerate()
        .map(|(i, e)| {
            world
                .spawn((
                    Name::new(e.id),
                    LobbyEntry {
                        experience: e.id.into(),
                        order: i as i32 * 10,
                        ..default()
                    },
                ))
                .id()
        })
        .collect();
    world.spawn(Name::new("Lobby")).add_children(&entries);
    bsn(
        &app,
        "// bevaru's lobby: one LobbyEntry per card. Change `order` to move a card,\n\
         // set `title`, `summary`, or `category` to reword it, or `hidden` to leave it\n\
         // out (it still opens by id). Generated by `cargo run --example generate_scenes`.",
    )
}

/// A camera looking at the origin from `eye`, and a key light.
fn stage(world: &mut World, eye: Vec3) {
    stage_at(world, eye, Vec3::ZERO);
}

/// A camera looking at `target` from `eye`, and a key light.
fn stage_at(world: &mut World, eye: Vec3, target: Vec3) {
    world.spawn((
        Name::new("Camera"),
        Camera3d::default(),
        Transform::from_translation(eye).looking_at(target, Vec3::Z),
        Visibility::Visible,
    ));
    world.spawn((
        Name::new("Key light"),
        DirectionalLight {
            illuminance: 7000.0,
            ..default()
        },
        Transform::default().looking_to(Vec3::new(0.55, 1.0, -0.75), Vec3::Z),
        Visibility::Visible,
    ));
}

/// `examples/perceptron.bsn`.
pub fn perceptron() -> String {
    let mut app = world();
    let world = app.world_mut();
    stage(world, Vec3::new(-4.0, -13.0, 3.0));
    world.spawn((
        Name::new("Perceptron"),
        PerceptronDiagram::default(),
        Transform::from_xyz(-0.6, 0.0, 0.0),
        Visibility::Visible,
    ));
    bsn(
        &app,
        "// A bevaru PerceptronDiagram. Edit its weights, bias, and activation in the\n\
         // inspector, then Play (\"Perceptron example\") to see it built.",
    )
}

/// `examples/loss-shapes.bsn`.
pub fn loss_shapes() -> String {
    let mut app = world();
    let world = app.world_mut();
    stage_at(world, Vec3::new(0.0, -9.5, 5.0), Vec3::new(0.0, 0.0, 0.6));
    for (i, view) in [
        "probability-vs-truth-cross-entropy",
        "two-scores-hinge",
        "prediction-vs-truth-huber",
    ]
    .into_iter()
    .enumerate()
    {
        world.spawn((
            Name::new(view),
            LossShapeSurface {
                view: view.into(),
                ..default()
            },
            Transform::from_xyz((i as f32 - 1.0) * 4.0, 0.0, 0.0).with_scale(Vec3::splat(0.33)),
            Visibility::Visible,
        ));
    }
    bsn(
        &app,
        "// Three bevaru LossShapeSurfaces. Change `view` to any loss-shape id (the\n\
         // capability manifest lists them), then Play (\"Loss shapes example\").",
    )
}
