//! Generators for the reference docs in `docs/agents/`.
//!
//! Everything here is derived from [`builtin_manifest`], so it can't drift
//! from the code. `cargo run -p bevaru-mcp -- gen-docs` writes the files, and
//! `tests/agent_docs.rs` fails when the committed files differ.

use std::fmt::Write as _;
use std::path::Path;

use super::{Manifest, ParamInfo, builtin_manifest};

/// The command that regenerates every file from [`generated_files`].
pub const GENERATE_COMMAND: &str = "cargo run -p bevaru-mcp -- gen-docs";

fn notice() -> String {
    format!("Generated by `{GENERATE_COMMAND}` from the code. Do not edit by hand.")
}

/// Hand-written docs whose code blocks are filled from compiled examples
/// (see [`expand_includes`]).
pub const DOCS_WITH_INCLUDES: [&str; 3] = [
    "docs/agents/guide.md",
    "docs/agents/recipes/train-headlessly.md",
    "docs/agents/recipes/add-an-experience.md",
];

/// Every generated file: `(path relative to the repository root, contents)`.
/// `root` is the repository root, for docs that include example code.
pub fn generated_files(root: &Path) -> Vec<(&'static str, String)> {
    let manifest = builtin_manifest();
    let mut files = vec![
        (
            "docs/agents/capabilities.json",
            capabilities_json(&manifest),
        ),
        ("docs/agents/capabilities.md", capabilities_md(&manifest)),
    ];
    for path in DOCS_WITH_INCLUDES {
        let text =
            std::fs::read_to_string(root.join(path)).unwrap_or_else(|e| panic!("{path}: {e}"));
        let expanded = expand_includes(&text, |file| std::fs::read_to_string(root.join(file)))
            .unwrap_or_else(|e| panic!("{path}: {e}"));
        files.push((path, expanded));
    }
    files
}

/// Replace the fenced code block after each `<!-- include: path -->` line
/// with that file's contents, so a doc's code is always code that compiles.
pub fn expand_includes(
    text: &str,
    read: impl Fn(&str) -> std::io::Result<String>,
) -> Result<String, String> {
    let mut out = String::new();
    let mut lines = text.lines().peekable();
    while let Some(line) = lines.next() {
        out.push_str(line);
        out.push('\n');
        let Some(file) = line
            .trim()
            .strip_prefix("<!-- include:")
            .and_then(|r| r.strip_suffix("-->"))
            .map(str::trim)
        else {
            continue;
        };
        let fence = lines
            .next()
            .filter(|l| l.starts_with("```"))
            .ok_or_else(|| {
                format!("`<!-- include: {file} -->` must be followed by a code fence")
            })?;
        // Skip the old block, up to and including its closing fence.
        loop {
            match lines.next() {
                Some(l) if l.trim() == "```" => break,
                Some(_) => {}
                None => return Err(format!("unclosed code block after include of {file}")),
            }
        }
        let code = read(file).map_err(|e| format!("{file}: {e}"))?;
        out.push_str(fence);
        out.push('\n');
        out.push_str(code.trim_end());
        out.push_str("\n```\n");
    }
    Ok(out)
}

/// The manifest as pretty JSON, with a `$comment` naming the generator.
pub fn capabilities_json(manifest: &Manifest) -> String {
    let mut value = serde_json::to_value(manifest).expect("manifest serializes");
    value
        .as_object_mut()
        .expect("manifest is an object")
        .insert("$comment".into(), notice().into());
    let mut out = serde_json::to_string_pretty(&value).expect("value serializes");
    out.push('\n');
    out
}

fn range(p: &ParamInfo) -> String {
    match (p.minimum, p.exclusive_minimum, p.maximum) {
        (Some(min), true, None) => format!("> {min}"),
        (Some(min), false, None) => format!("≥ {min}"),
        (Some(min), ex, Some(max)) => format!("{min}{} … {max}", if ex { " (excl.)" } else { "" }),
        (None, _, Some(max)) => format!("≤ {max}"),
        (None, _, None) => "any".into(),
    }
}

fn num(v: f64) -> String {
    if v != 0.0 && (v.abs() >= 1e5 || v.abs() < 1e-3) {
        format!("{v:e}")
    } else {
        format!("{v}")
    }
}

fn params(list: &[ParamInfo]) -> String {
    if list.is_empty() {
        return "—".into();
    }
    list.iter()
        .map(|p| match p.default {
            Some(d) => format!("`{}` {} (default {})", p.id, range(p), num(d)),
            None => format!("`{}` {}", p.id, range(p)),
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

/// A readable rendering of the manifest.
pub fn capabilities_md(m: &Manifest) -> String {
    let mut o = String::new();
    let w = &mut o;
    let _ = writeln!(w, "<!-- {} -->\n", notice());
    let _ = writeln!(w, "# bevaru capabilities\n");
    let _ = writeln!(
        w,
        "Reference for bevaru {}, manifest schema version {}. The same data is in [`capabilities.json`](capabilities.json), with JSON Schemas for every request type. Start from the [agent guide](guide.md).\n",
        m.bevaru_version, m.schema_version
    );

    let _ = writeln!(w, "## Losses\n");
    let _ = writeln!(
        w,
        "Regression losses are functions of the residual r = ŷ − y; classification losses of the margin m = y·f(x), with y ∈ {{−1, +1}}.\n"
    );
    let _ = writeln!(
        w,
        "| id | name | task | formula | hyperparameters | trains |"
    );
    let _ = writeln!(
        w,
        "| -- | ---- | ---- | ------- | --------------- | ------ |"
    );
    for l in &m.losses {
        let trains = match (&l.model, l.trainable) {
            (Some(model), true) => format!("`{model}`"),
            _ => "plot only".into(),
        };
        let _ = writeln!(
            w,
            "| `{}` | {} | {} | {} | {} | {} |",
            l.id,
            cell(&l.name),
            l.task,
            cell(&l.formula),
            params(&l.hyperparameters),
            trains
        );
    }

    let _ = writeln!(w, "\n## Models\n");
    for model in &m.models {
        let _ = writeln!(w, "### `{}`: {}\n", model.id, model.name);
        let _ = writeln!(w, "{}\n", model.description);
        let losses: Vec<String> = model.losses.iter().map(|l| format!("`{l}`")).collect();
        let _ = writeln!(w, "- **Task:** {}", model.task);
        let _ = writeln!(
            w,
            "- **Losses:** {} (default `{}`)",
            losses.join(", "),
            model.default_loss
        );
        let _ = writeln!(
            w,
            "- **Hyperparameters:** {}\n",
            params(&model.hyperparameters).replace("<br>", "; ")
        );
    }

    let _ = writeln!(w, "## Datasets\n");
    let _ = writeln!(
        w,
        "| kind | task | features | classes | default view | description |"
    );
    let _ = writeln!(
        w,
        "| ---- | ---- | -------- | ------- | ------------ | ----------- |"
    );
    for d in &m.datasets {
        let requires = d
            .requires_feature
            .as_ref()
            .map(|f| format!(" Needs the `{f}` feature."))
            .unwrap_or_default();
        let classes = if d.classes.is_empty() {
            "—".into()
        } else {
            d.classes.join(", ")
        };
        let _ = writeln!(
            w,
            "| `{}` | {} | {} | {} | {} | {}{} |",
            d.id,
            d.task,
            d.features,
            cell(&classes),
            cell(&d.default_view),
            cell(&d.description),
            requires
        );
    }

    let _ = writeln!(w, "\n## Views\n");
    for v in &m.views {
        let _ = writeln!(w, "- `{}`: {}", v.id, v.description);
    }

    let _ = writeln!(w, "\n## Loss shapes\n");
    let _ = writeln!(
        w,
        "3-D views of each loss over two inputs, for `sample_loss_shape` and `render_loss_shape`. Heights above the cap are clipped and flagged.\n"
    );
    let _ = writeln!(
        w,
        "| id | family | losses | x axis | y axis | height | hyperparameters |"
    );
    let _ = writeln!(
        w,
        "| -- | ------ | ------ | ------ | ------ | ------ | --------------- |"
    );
    let axis = |a: &super::ShapeAxisInfo| {
        format!("{} ({}), {} … {}", a.symbol, a.name, num(a.min), num(a.max))
    };
    for v in &m.loss_shapes {
        let mut height = v.height_label.clone();
        if let Some(cap) = v.cap {
            height.push_str(&format!(", capped at {}", num(cap)));
        }
        let hyper = if v.hyperparameters.is_empty() {
            "—".to_string()
        } else {
            v.hyperparameters
                .iter()
                .map(|h| format!("`{h}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            w,
            "| `{}` | {} | {} | {} | {} | {} | {} |",
            v.id,
            v.family,
            v.losses.join(", "),
            cell(&axis(&v.x_axis)),
            cell(&axis(&v.y_axis)),
            cell(&height),
            hyper
        );
    }
    let _ = writeln!(w);
    for v in &m.loss_shapes {
        let _ = writeln!(w, "- **`{}`**: {}", v.id, v.caption);
        if let Some(slice) = &v.slice {
            let _ = writeln!(w, "  The 2-D curve is the slice {slice}");
        }
    }

    let _ = writeln!(w, "\n## Sweep parameters\n");
    let _ = writeln!(w, "| id | name | applies to | default range |");
    let _ = writeln!(w, "| -- | ---- | ---------- | ------------- |");
    for p in &m.sweep_parameters {
        let applies: Vec<String> = p.applies_to.iter().map(|l| format!("`{l}`")).collect();
        let _ = writeln!(
            w,
            "| `{}` | {} | {} | {} … {}{} |",
            p.id,
            cell(&p.name),
            applies.join(", "),
            num(p.default_from),
            num(p.default_to),
            if p.default_log { " (log)" } else { "" }
        );
    }

    let _ = writeln!(w, "\n## Experiences\n");
    let _ = writeln!(w, "Open one with `cargo run -- <id>`, or from the lobby.\n");
    let _ = writeln!(w, "| id | title | category | kind | summary |");
    let _ = writeln!(w, "| -- | ----- | -------- | ---- | ------- |");
    for e in &m.experiences {
        let mut summary = e.summary.clone();
        if let Some(f) = &e.requires_feature {
            let _ = write!(summary, " Needs the `{f}` feature.");
        }
        if let Some(n) = &e.note {
            let _ = write!(summary, " {n}");
        }
        let _ = writeln!(
            w,
            "| `{}` | {} | {} | {} | {} |",
            e.id,
            cell(&e.title),
            cell(&e.category),
            e.kind,
            cell(&summary)
        );
    }

    let _ = writeln!(w, "\n## Messages\n");
    let _ = writeln!(
        w,
        "Send these with a Bevy `MessageWriter` to drive bevaru from your own systems.\n"
    );
    for msg in &m.messages {
        let _ = writeln!(w, "- **`{}`**: {}", msg.name, msg.description);
        for (variant, description) in &msg.variants {
            let _ = writeln!(w, "  - `{variant}`: {description}");
        }
    }

    let _ = writeln!(w, "\n## Remote methods\n");
    let _ = writeln!(
        w,
        "A window started with `cargo run --features remote -- --remote` serves these Bevy Remote Protocol (JSON-RPC 2.0) methods on `http://127.0.0.1:15702`, alongside BRP's built-in `world.*` methods. The MCP server's `app_*` tools call them for you; see [drive a running app](recipes/drive-a-running-app.md).\n"
    );
    for r in &m.remote_methods {
        let _ = writeln!(w, "- `{}`: {}", r.method, cell(&r.description));
    }

    let _ = writeln!(w, "\n## Tools\n");
    let _ = writeln!(
        w,
        "Served by the `bevaru-mcp` MCP server. Each tool's input type is listed below; its JSON Schema is in [`capabilities.json`](capabilities.json) under `schemas`.\n"
    );
    let _ = writeln!(w, "| tool | group | input | description |");
    let _ = writeln!(w, "| ---- | ----- | ----- | ----------- |");
    for t in &m.tools {
        let app = if t.requires_app {
            " *(running app only)*"
        } else {
            ""
        };
        let _ = writeln!(
            w,
            "| `{}` | {} | `{}` | {}{} |",
            t.name,
            t.group,
            t.input_type,
            cell(&t.description),
            app
        );
    }
    o
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn includes_replace_the_block_and_are_idempotent() {
        let doc = "intro\n<!-- include: a.rs -->\n```rust\nold\nlines\n```\noutro\n";
        let read = |f: &str| {
            assert_eq!(f, "a.rs");
            Ok("fn main() {}\n".to_string())
        };
        let once = expand_includes(doc, read).unwrap();
        assert_eq!(
            once,
            "intro\n<!-- include: a.rs -->\n```rust\nfn main() {}\n```\noutro\n"
        );
        assert_eq!(expand_includes(&once, read).unwrap(), once);
        assert!(expand_includes("<!-- include: a.rs -->\nno fence\n", read).is_err());
    }
}
